repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-docstring-first
    - id: check-toml
    - id: pretty-format-json
      args:
        - "--autofix"
    - id: check-json
    - id: detect-private-key


- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
    - id: mypy


- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade


- repo: https://github.com/streetsidesoftware/cspell-cli
  rev: v9.2.0
  hooks:
  - id: cspell


- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.2.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
